name: the/args
version: 0.2.0
description: Command line arguments parser and tools
license: MIT
main: src/args

files:
  - src/arg
  - src/args
  - src/config
  - src/state

packages:
  the/error: 1.1.3
