name: the/parser
version: 0.4.7
description: The programming language parser
license: MIT
main: src/main

packages:
  the/testing: 0.3.2

scripts:
  update-parser-tests: the run scripts/update-parser-tests
  update-tokenizer-tests: the run scripts/update-tokenizer-tests
