/**
 * Copyright (c) Aaron Delasy
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

#include <duc/testing.h>
#include "../../src/lexer/litint.h"
#include "../utilities.h"

DUC_TEST(lexer_litint, works) {
  LEXER_FSS("0", LEXER_LITINT_DEC);
  LEXER_FSS("1", LEXER_LITINT_DEC);
  LEXER_FSS("9", LEXER_LITINT_DEC);
  LEXER_FSS("2147483647", LEXER_LITINT_DEC);

  LEXER_FSS("0O0", LEXER_LITINT_OCT);
  LEXER_FSS("0o0", LEXER_LITINT_OCT);
  LEXER_FSS("01", LEXER_LITINT_OCT);
  LEXER_FSS("0O1", LEXER_LITINT_OCT);
  LEXER_FSS("0o1", LEXER_LITINT_OCT);
  LEXER_FSS("07", LEXER_LITINT_OCT);
  LEXER_FSS("0O7", LEXER_LITINT_OCT);
  LEXER_FSS("0o7", LEXER_LITINT_OCT);
  LEXER_FSS("017777777777", LEXER_LITINT_OCT);
  LEXER_FSS("0O17777777777", LEXER_LITINT_OCT);
  LEXER_FSS("0o17777777777", LEXER_LITINT_OCT);

  LEXER_FSS("0B0", LEXER_LITINT_BIN);
  LEXER_FSS("0b0", LEXER_LITINT_BIN);
  LEXER_FSS("0B1", LEXER_LITINT_BIN);
  LEXER_FSS("0b1", LEXER_LITINT_BIN);
  LEXER_FSS("0B01111111111111111111111111111111", LEXER_LITINT_BIN);
  LEXER_FSS("0b01111111111111111111111111111111", LEXER_LITINT_BIN);

  LEXER_FSS("0X0", LEXER_LITINT_HEX);
  LEXER_FSS("0x0", LEXER_LITINT_HEX);
  LEXER_FSS("0X1", LEXER_LITINT_HEX);
  LEXER_FSS("0x1", LEXER_LITINT_HEX);
  LEXER_FSS("0X9", LEXER_LITINT_HEX);
  LEXER_FSS("0x9", LEXER_LITINT_HEX);
  LEXER_FSS("0XF", LEXER_LITINT_HEX);
  LEXER_FSS("0xF", LEXER_LITINT_HEX);
  LEXER_FSS("0X7FFFFFFF", LEXER_LITINT_HEX);
  LEXER_FSS("0x7FFFFFFF", LEXER_LITINT_HEX);
}

int main () {
  DUC_TEST_RUN(lexer_litint, works);
}
